import 'package:flutter/material.dart';

const defaultTextColor = Color(0xff191919);

// -------------------------------- 한글서체 Pretendard --------------------------------------------------------


const textThemeKo = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'Pretendard',
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 64.0 * 2,
    letterSpacing: -1.6,
    height: 80 / 64,
    color: defaultTextColor,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 52.0 * 2,
    letterSpacing: -1.3,
    height: 68 / 52,
    color: defaultTextColor,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 7.0 * 2,
    letterSpacing: -0.14,
    height: 8 / 7,
    color: defaultTextColor,
  ),
  // Sign up headline
  headlineLarge: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 48.0 * 2,
    letterSpacing: -0.72,
    height: 56 / 48,
    color: defaultTextColor,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 30.0 * 2,
    letterSpacing: -0.24,
    height: 36 / 30,
    color: defaultTextColor,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 48,
    letterSpacing: -0.0,
    height: 28 / 24,
    color: defaultTextColor,
  ),

  titleLarge: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 40,
    letterSpacing: -0.0,
    height: 23 / 17,
    color: defaultTextColor,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 36,
    letterSpacing: -0.24,
    height: 12 / 12,
    color: defaultTextColor,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 32,
    letterSpacing: -0.20,
    height: 12 / 10,
    color: defaultTextColor,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Pretendard',
    fontSize: 30,
    fontWeight: FontWeight.w400,
    height: 12 / 8,
    letterSpacing: -0.16,
    color: defaultTextColor,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Pretendard',
    fontSize: 28,
    fontWeight: FontWeight.w400,
    height: 12 / 7,
    letterSpacing: -0.14,
    color: defaultTextColor,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Pretendard',
    fontSize: 26,
    fontWeight: FontWeight.w400,
    height: 8 / 6,
    letterSpacing: -0.12,
    color: defaultTextColor,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Pretendard',
    fontSize: 24,
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    letterSpacing: -0.16,
    height: 12 / 8,
    color: defaultTextColor,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 22,
    letterSpacing: -0.14,
    height: 10 / 7,
    color: defaultTextColor,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Pretendard',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 20,
    letterSpacing: -0.10,
    height: 8 / 5,
    color: defaultTextColor,
  ),
);

// -------------------------------- 영문서체 Montserrat --------------------------------------------------------

const textThemeEn = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 64.0 * 2,
    letterSpacing: -1.6,
    height: 80 / 64,
    color: defaultTextColor,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 52.0 * 2,
    letterSpacing: -1.3,
    height: 68 / 52,
    color: defaultTextColor,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 7.0 * 2,
    letterSpacing: -0.14,
    height: 8 / 7,
    color: defaultTextColor,
  ),
  // Sign up headline
  headlineLarge: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 48.0 * 2,
    letterSpacing: -0.72,
    height: 56 / 48,
    color: defaultTextColor,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 30.0 * 2,
    letterSpacing: -0.24,
    height: 36 / 30,
    color: defaultTextColor,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 24.0 * 2,
    letterSpacing: -0.0,
    height: 28 / 24,
    color: defaultTextColor,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 17.0 * 2,
    letterSpacing: -0.0,
    height: 23 / 17,
    color: defaultTextColor,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 12.0 * 2,
    letterSpacing: -0.24,
    height: 12 / 12,
    color: defaultTextColor,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 10.0 * 2,
    letterSpacing: -0.20,
    height: 12 / 10,
    color: defaultTextColor,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 8 * 2,
    fontWeight: FontWeight.w400,
    height: 12 / 8,
    letterSpacing: -0.16,
    color: defaultTextColor,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 7 * 2,
    fontWeight: FontWeight.w400,
    height: 12 / 7,
    letterSpacing: -0.14,
    color: defaultTextColor,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 6 * 2,
    fontWeight: FontWeight.w400,
    height: 8 / 6,
    letterSpacing: -0.12,
    color: defaultTextColor,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 30,
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    letterSpacing: -0.16,
    height: 12 / 8,
    color: defaultTextColor,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 28,
    letterSpacing: -0.14,
    height: 10 / 7,
    color: defaultTextColor,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 24,
    letterSpacing: -0.10,
    height: 8 / 5,
    color: defaultTextColor,
  ),
);
